/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.praktikum3;

/**
 *
 * @author farhandwihartanto
 */
public class File4 extends javax.swing.JFrame {

    /**
     * Creates new form File4
     */
    public File4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        bgNumber = new javax.swing.ButtonGroup();
        rbSatu = new javax.swing.JRadioButton();
        rbDua = new javax.swing.JRadioButton();
        rbTiga = new javax.swing.JRadioButton();
        rbEnam = new javax.swing.JRadioButton();
        rbTujuh = new javax.swing.JRadioButton();
        rbDelapan = new javax.swing.JRadioButton();
        rbEmpat = new javax.swing.JRadioButton();
        rbLima = new javax.swing.JRadioButton();
        rbSembilan = new javax.swing.JRadioButton();
        rbSepuluh = new javax.swing.JRadioButton();
        rbSebelas = new javax.swing.JRadioButton();
        rbDuabelas = new javax.swing.JRadioButton();
        rbTigabelas = new javax.swing.JRadioButton();
        rbEmpatbelas = new javax.swing.JRadioButton();
        rbLimabelas = new javax.swing.JRadioButton();
        btnPilih = new javax.swing.JButton();
        txtHasil = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgNumber.add(rbSatu);
        rbSatu.setText("01");

        bgNumber.add(rbDua);
        rbDua.setText("02");

        bgNumber.add(rbTiga);
        rbTiga.setText("03");

        bgNumber.add(rbEnam);
        rbEnam.setText("06");

        bgNumber.add(rbTujuh);
        rbTujuh.setText("07");

        bgNumber.add(rbDelapan);
        rbDelapan.setText("08");

        bgNumber.add(rbEmpat);
        rbEmpat.setText("04");

        bgNumber.add(rbLima);
        rbLima.setText("05");

        bgNumber.add(rbSembilan);
        rbSembilan.setText("09");

        bgNumber.add(rbSepuluh);
        rbSepuluh.setText("10");

        bgNumber.add(rbSebelas);
        rbSebelas.setText("11");

        bgNumber.add(rbDuabelas);
        rbDuabelas.setText("12");

        bgNumber.add(rbTigabelas);
        rbTigabelas.setText("13");

        bgNumber.add(rbEmpatbelas);
        rbEmpatbelas.setText("14");

        bgNumber.add(rbLimabelas);
        rbLimabelas.setText("15");
        rbLimabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLimabelasActionPerformed(evt);
            }
        });

        btnPilih.setText("PILIH");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        btnClear.setText("BERSIH");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLima, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSebelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDuabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbEmpatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLimabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtHasil)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addGap(106, 106, 106)
                        .addComponent(btnPilih)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbSebelas)
                        .addGap(36, 36, 36)
                        .addComponent(rbDuabelas)
                        .addGap(36, 36, 36)
                        .addComponent(rbTigabelas)
                        .addGap(36, 36, 36)
                        .addComponent(rbEmpatbelas)
                        .addGap(36, 36, 36)
                        .addComponent(rbLimabelas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbEnam)
                                .addGap(36, 36, 36)
                                .addComponent(rbTujuh)
                                .addGap(36, 36, 36)
                                .addComponent(rbDelapan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSatu)
                                .addGap(36, 36, 36)
                                .addComponent(rbDua)
                                .addGap(36, 36, 36)
                                .addComponent(rbTiga)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbSembilan)
                                .addGap(36, 36, 36)
                                .addComponent(rbSepuluh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbEmpat)
                                .addGap(36, 36, 36)
                                .addComponent(rbLima)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        // Deklarasi Variable
        String strPilih;

        // Memeriksa apakah salah satu tombol radio terpilih
        if (rbSatu.isSelected() || rbDua.isSelected() || rbTiga.isSelected() || rbEmpat.isSelected() || rbLima.isSelected()
                || rbEnam.isSelected() || rbTujuh.isSelected() || rbDelapan.isSelected() || rbSembilan.isSelected() || rbSepuluh.isSelected()) {

            strPilih = "Input anda kurang dari 10";

        } else {
            strPilih = "Input anda terlalu banyak";
        }
        txtHasil.setText(strPilih);
    }//GEN-LAST:event_btnPilihActionPerformed

    private void rbLimabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLimabelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLimabelasActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        rbSatu.setSelected(false);
        rbDua.setSelected(false);
        rbTiga.setSelected(false);
        rbEmpat.setSelected(false);
        rbLima.setSelected(false);
        rbEnam.setSelected(false);
        rbTujuh.setSelected(false);
        rbDelapan.setSelected(false);
        rbSembilan.setSelected(false);
        rbSepuluh.setSelected(false);
        rbSepuluh.setSelected(false);
        rbSebelas.setSelected(false);
        rbDuabelas.setSelected(false);
        rbTigabelas.setSelected(false);
        rbEmpatbelas.setSelected(false);
        rbLimabelas.setSelected(false);

        // Menghapus teks pada JTextField
        txtHasil.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(File4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(File4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(File4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(File4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new File4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNumber;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPilih;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButton rbDelapan;
    private javax.swing.JRadioButton rbDua;
    private javax.swing.JRadioButton rbDuabelas;
    private javax.swing.JRadioButton rbEmpat;
    private javax.swing.JRadioButton rbEmpatbelas;
    private javax.swing.JRadioButton rbEnam;
    private javax.swing.JRadioButton rbLima;
    private javax.swing.JRadioButton rbLimabelas;
    private javax.swing.JRadioButton rbSatu;
    private javax.swing.JRadioButton rbSebelas;
    private javax.swing.JRadioButton rbSembilan;
    private javax.swing.JRadioButton rbSepuluh;
    private javax.swing.JRadioButton rbTiga;
    private javax.swing.JRadioButton rbTigabelas;
    private javax.swing.JRadioButton rbTujuh;
    private javax.swing.JTextField txtHasil;
    // End of variables declaration//GEN-END:variables
}
