/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.praktikum4;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author farhandwihartanto
 */
public class File3 extends javax.swing.JFrame {

    /**
     * Creates new form File3
     */
    public File3() {
        initComponents();
        image.setIcon(new javax.swing.ImageIcon("./assets/Logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        drinkImage1 = new javax.swing.JLabel();
        foodImage1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        cbUlarPanggang = new javax.swing.JCheckBox();
        cbPiranhaPresto = new javax.swing.JCheckBox();
        cbSupKelelawar = new javax.swing.JCheckBox();
        cbTikusGoreng = new javax.swing.JCheckBox();
        cbDarahTiramisu = new javax.swing.JCheckBox();
        cbBisaCobraGembira = new javax.swing.JCheckBox();
        cbKopiBasiKecoak = new javax.swing.JCheckBox();
        cbAirParetAmericano = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblResultName = new javax.swing.JLabel();
        lblResultAddress = new javax.swing.JLabel();
        foodImage4 = new javax.swing.JLabel();
        foodImage2 = new javax.swing.JLabel();
        foodImage3 = new javax.swing.JLabel();
        drinkImage3 = new javax.swing.JLabel();
        drinkImage4 = new javax.swing.JLabel();
        drinkImage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Makanan :");

        jLabel2.setText("Minuman :");

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Ente Arep Eat Opo Dino Iki?");

        jLabel4.setText("Makanan");

        drinkImage1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        foodImage1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Minuman");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Detail Pesanan");

        jLabel3.setText("Nama        :");

        jLabel6.setText("Alamat      :");

        cbUlarPanggang.setText("Ular Panggang");

        cbPiranhaPresto.setText("Piranha Presto");

        cbSupKelelawar.setText("Sup Kelelawar");

        cbTikusGoreng.setText("Tikus Goreng");

        cbDarahTiramisu.setText("Darah Tiramisu");

        cbBisaCobraGembira.setText("Bisa Cobra Gembira");

        cbKopiBasiKecoak.setText("Kopi Basi + Kecoak");

        cbAirParetAmericano.setText("Air Paret Americano");

        jLabel7.setText("Nama        :");

        jLabel10.setText("Alamat      :");

        lblResultName.setText("-");

        lblResultAddress.setText("-");

        foodImage4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        foodImage2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        foodImage3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        drinkImage3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        drinkImage4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        drinkImage2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAirParetAmericano)
                                    .addComponent(cbBisaCobraGembira)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTikusGoreng)
                                    .addComponent(cbPiranhaPresto))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDarahTiramisu)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(btnPesan))
                                    .addComponent(cbKopiBasiKecoak)))
                            .addComponent(cbUlarPanggang)
                            .addComponent(cbSupKelelawar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(tfAddress))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drinkImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(drinkImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(drinkImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(drinkImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblResultName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foodImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foodImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foodImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foodImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)))
                .addGap(522, 522, 522))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbPiranhaPresto)
                            .addComponent(cbUlarPanggang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSupKelelawar)
                            .addComponent(cbTikusGoreng))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbBisaCobraGembira)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbAirParetAmericano)
                                    .addComponent(cbKopiBasiKecoak)))
                            .addComponent(cbDarahTiramisu))
                        .addGap(37, 37, 37)
                        .addComponent(btnPesan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10))
                                .addComponent(lblResultAddress))
                            .addComponent(lblResultName))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drinkImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
//        if food selected
        if (cbPiranhaPresto.isSelected()) {
            selectedFood[0] = cbPiranhaPresto.getText().toLowerCase();
        }
        if (cbUlarPanggang.isSelected()) {
            selectedFood[1] = cbUlarPanggang.getText().toLowerCase();
        }
        if (cbTikusGoreng.isSelected()) {
            selectedFood[2] = cbTikusGoreng.getText().toLowerCase();
        }
        if (cbSupKelelawar.isSelected()) {
            selectedFood[3] = cbSupKelelawar.getText().toLowerCase();
        }

        //        if drink selected
        if (cbBisaCobraGembira.isSelected()) {
            selectedDrink[0] = cbBisaCobraGembira.getText().toLowerCase();
        }
        if (cbDarahTiramisu.isSelected()) {
            selectedDrink[1] = cbDarahTiramisu.getText().toLowerCase();
        }
        if (cbAirParetAmericano.isSelected()) {
            selectedDrink[2] = cbAirParetAmericano.getText().toLowerCase();
        }
        if (cbKopiBasiKecoak.isSelected()) {
            selectedDrink[3] = cbKopiBasiKecoak.getText().toLowerCase();
        }

        String regex = "^[^\\s].*";

        Pattern pattern = Pattern.compile(regex);

        Matcher nameMatcher = pattern.matcher(tfName.getText());
        Matcher addressMatcher = pattern.matcher(tfAddress.getText());

        if (tfName.getText().length() < 1 || tfAddress.getText().length() < 1 || !nameMatcher.matches() || !addressMatcher.matches()) {
            JOptionPane.showMessageDialog(null, "Waduh jangan bercanda Mas!!");
        } else {
            lblResultName.setText(tfName.getText());
            lblResultAddress.setText(tfAddress.getText());

            foodImage1.setIcon(new javax.swing.ImageIcon("./assets/" + selectedFood[0] + ".jpg"));
            foodImage2.setIcon(new javax.swing.ImageIcon("./assets/" + selectedFood[1] + ".jpg"));
            foodImage3.setIcon(new javax.swing.ImageIcon("./assets/" + selectedFood[2] + ".jpg"));
            foodImage4.setIcon(new javax.swing.ImageIcon("./assets/" + selectedFood[3] + ".jpg"));
            drinkImage1.setIcon(new javax.swing.ImageIcon("./assets/" + selectedDrink[0] + ".jpg"));
            drinkImage2.setIcon(new javax.swing.ImageIcon("./assets/" + selectedDrink[1] + ".jpg"));
            drinkImage3.setIcon(new javax.swing.ImageIcon("./assets/" + selectedDrink[2] + ".jpg"));
            drinkImage4.setIcon(new javax.swing.ImageIcon("./assets/" + selectedDrink[3] + ".jpg"));
        }

    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(File3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(File3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(File3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(File3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new File3().setVisible(true);
            }
        });
    }

    private String strMakanan;
    private String[] selectedFood = new String[4];
    private String strMinuman;
    private String[] selectedDrink = new String[4];
    private String strSayuran;
    private String selectedVeget;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JCheckBox cbAirParetAmericano;
    private javax.swing.JCheckBox cbBisaCobraGembira;
    private javax.swing.JCheckBox cbDarahTiramisu;
    private javax.swing.JCheckBox cbKopiBasiKecoak;
    private javax.swing.JCheckBox cbPiranhaPresto;
    private javax.swing.JCheckBox cbSupKelelawar;
    private javax.swing.JCheckBox cbTikusGoreng;
    private javax.swing.JCheckBox cbUlarPanggang;
    private javax.swing.JLabel drinkImage1;
    private javax.swing.JLabel drinkImage2;
    private javax.swing.JLabel drinkImage3;
    private javax.swing.JLabel drinkImage4;
    private javax.swing.JLabel foodImage1;
    private javax.swing.JLabel foodImage2;
    private javax.swing.JLabel foodImage3;
    private javax.swing.JLabel foodImage4;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblResultAddress;
    private javax.swing.JLabel lblResultName;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
