/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.praktikum8;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author farhandwihartanto
 */
public class BangunDatar extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public BangunDatar() {
        initComponents();
        this.isFieldVisible(false, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData1 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtData1 = new javax.swing.JTextField();
        txtData2 = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        lblData3 = new javax.swing.JLabel();
        txtData3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnProses = new javax.swing.JMenu();
        mnItClear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnItHitung = new javax.swing.JMenu();
        mnItLuasPersegiPanjang = new javax.swing.JMenuItem();
        mnItLuasSegitiga = new javax.swing.JMenuItem();
        mnItLuasLingkaran = new javax.swing.JMenuItem();
        mnItHitung1 = new javax.swing.JMenu();
        mnItKelilingPersegiPanjang = new javax.swing.JMenuItem();
        mnItSegitiga = new javax.swing.JMenuItem();
        mnItLingkaran = new javax.swing.JMenuItem();
        mnBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblData1.setText("Data 1");

        lblData2.setText("Data 2");

        jLabel3.setText("Hasil");

        lblData3.setText("Data 3");

        mnFile.setText("File");
        jMenuBar1.add(mnFile);

        mnProses.setText("Proses");

        mnItClear.setText("Clear");
        mnItClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItClearActionPerformed(evt);
            }
        });
        mnProses.add(mnItClear);
        mnProses.add(jSeparator1);

        mnItHitung.setText("Luas");

        mnItLuasPersegiPanjang.setText("Persegi Panjang");
        mnItLuasPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItLuasPersegiPanjangActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItLuasPersegiPanjang);

        mnItLuasSegitiga.setText("Segi Tiga");
        mnItLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItLuasSegitigaActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItLuasSegitiga);

        mnItLuasLingkaran.setText("Lingkaran");
        mnItLuasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItLuasLingkaranActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItLuasLingkaran);

        mnProses.add(mnItHitung);

        mnItHitung1.setText("Keliling");

        mnItKelilingPersegiPanjang.setText("Persegi Panjang");
        mnItKelilingPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItKelilingPersegiPanjangActionPerformed(evt);
            }
        });
        mnItHitung1.add(mnItKelilingPersegiPanjang);

        mnItSegitiga.setText("Segi Tiga");
        mnItSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItSegitigaActionPerformed(evt);
            }
        });
        mnItHitung1.add(mnItSegitiga);

        mnItLingkaran.setText("Lingkaran");
        mnItLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItLingkaranActionPerformed(evt);
            }
        });
        mnItHitung1.add(mnItLingkaran);

        mnProses.add(mnItHitung1);

        jMenuBar1.add(mnProses);

        mnBantuan.setText("Bantuan");
        jMenuBar1.add(mnBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData1)
                        .addGap(103, 103, 103)
                        .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData2)
                            .addComponent(jLabel3)
                            .addComponent(lblData3))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtData2)
                            .addComponent(txtData3))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData1)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData2)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData3)
                    .addComponent(txtData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isFieldVisible(boolean visible, int numberOfField) {
        JLabel[] labelFields = {lblData1, lblData2, lblData3};
        JTextField[] textFields = {txtData1, txtData2, txtData3};

        for (int i = 0; i < labelFields.length; i++) {
            // Is field should be enabled or disabled based on index
            boolean shouldBeVisible = (i < numberOfField);

            // set visibility label and textField based on shouldBeVisible value
            labelFields[i].setVisible(shouldBeVisible && visible);
            textFields[i].setVisible(shouldBeVisible && visible);
        }
    }

    private String formatDecimal(double value) {
        return new DecimalFormat("##.##").format(value);
    }

    private void mnItLuasPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItLuasPersegiPanjangActionPerformed
        this.isFieldVisible(true, 2);
        lblData1.setText("Panjang");
        lblData2.setText("Lebar");
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(this.formatDecimal(dblData1 * dblData2));
    }//GEN-LAST:event_mnItLuasPersegiPanjangActionPerformed

    private void mnItLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItLuasSegitigaActionPerformed
        this.isFieldVisible(true, 2);

        lblData1.setText("Alas");
        lblData2.setText("Tinggi");
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(this.formatDecimal(dblData1 * dblData2 / 2));
    }//GEN-LAST:event_mnItLuasSegitigaActionPerformed

    private void mnItLuasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItLuasLingkaranActionPerformed
        this.isFieldVisible(true, 1);

        lblData1.setText("Jari-jari");
        double dblData1 = Double.parseDouble(txtData1.getText());

//        show
        txtHasil.setText(this.formatDecimal(Math.PI * dblData1 * dblData1));
    }//GEN-LAST:event_mnItLuasLingkaranActionPerformed

    private void mnItClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItClearActionPerformed
        txtData1.setText("");
        txtData2.setText("");
        txtHasil.setText("");
    }//GEN-LAST:event_mnItClearActionPerformed

    private void mnItKelilingPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItKelilingPersegiPanjangActionPerformed
        this.isFieldVisible(true, 2);
        lblData1.setText("Panjang");
        lblData2.setText("Lebar");
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(this.formatDecimal(2 * (dblData1 + dblData2)));
    }//GEN-LAST:event_mnItKelilingPersegiPanjangActionPerformed

    private void mnItSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItSegitigaActionPerformed
        this.isFieldVisible(true, 3);

        lblData1.setText("Sisi 1");
        lblData2.setText("Sisi 2");
        lblData3.setText("Sisi 3");
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());
        double dblData3 = Double.parseDouble(txtData3.getText());

//        show
        txtHasil.setText(this.formatDecimal(dblData1 + dblData2 + dblData3));
    }//GEN-LAST:event_mnItSegitigaActionPerformed

    private void mnItLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItLingkaranActionPerformed
        this.isFieldVisible(true, 1);

        lblData1.setText("Jari-jari");
        double dblData1 = Double.parseDouble(txtData1.getText());

//        show
        txtHasil.setText(this.formatDecimal(2 * Math.PI * dblData1));
    }//GEN-LAST:event_mnItLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JMenu mnBantuan;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnItClear;
    private javax.swing.JMenu mnItHitung;
    private javax.swing.JMenu mnItHitung1;
    private javax.swing.JMenuItem mnItKelilingPersegiPanjang;
    private javax.swing.JMenuItem mnItLingkaran;
    private javax.swing.JMenuItem mnItLuasLingkaran;
    private javax.swing.JMenuItem mnItLuasPersegiPanjang;
    private javax.swing.JMenuItem mnItLuasSegitiga;
    private javax.swing.JMenuItem mnItSegitiga;
    private javax.swing.JMenu mnProses;
    private javax.swing.JTextField txtData1;
    private javax.swing.JTextField txtData2;
    private javax.swing.JTextField txtData3;
    private javax.swing.JTextField txtHasil;
    // End of variables declaration//GEN-END:variables
}
