/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.praktikum8;

/**
 *
 * @author farhandwihartanto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtData1 = new javax.swing.JTextField();
        txtData2 = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnProses = new javax.swing.JMenu();
        mnItClear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnItHitung = new javax.swing.JMenu();
        mnItKali = new javax.swing.JMenuItem();
        mnItBagi = new javax.swing.JMenuItem();
        mnItTambah = new javax.swing.JMenuItem();
        mnItKurang = new javax.swing.JMenuItem();
        mnBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data 1");

        jLabel2.setText("Data 2");

        jLabel3.setText("Hasil");

        mnFile.setText("File");
        jMenuBar1.add(mnFile);

        mnProses.setText("Proses");

        mnItClear.setText("Clear");
        mnItClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItClearActionPerformed(evt);
            }
        });
        mnProses.add(mnItClear);
        mnProses.add(jSeparator1);

        mnItHitung.setText("Hitung");

        mnItKali.setText("Kali");
        mnItKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItKaliActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItKali);

        mnItBagi.setText("Bagi");
        mnItBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItBagiActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItBagi);

        mnItTambah.setText("Tambah");
        mnItTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItTambahActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItTambah);

        mnItKurang.setText("Kurang");
        mnItKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItKurangActionPerformed(evt);
            }
        });
        mnItHitung.add(mnItKurang);

        mnProses.add(mnItHitung);

        jMenuBar1.add(mnProses);

        mnBantuan.setText("Bantuan");
        jMenuBar1.add(mnBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtData2))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItKaliActionPerformed
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(Double.toString(dblData1 * dblData2));
    }//GEN-LAST:event_mnItKaliActionPerformed

    private void mnItBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItBagiActionPerformed
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(Double.toString(dblData1 / dblData2));
    }//GEN-LAST:event_mnItBagiActionPerformed

    private void mnItTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItTambahActionPerformed
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(Double.toString(dblData1 + dblData2));
    }//GEN-LAST:event_mnItTambahActionPerformed

    private void mnItKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItKurangActionPerformed
        double dblData1 = Double.parseDouble(txtData1.getText());
        double dblData2 = Double.parseDouble(txtData2.getText());

//        show
        txtHasil.setText(Double.toString(dblData1 - dblData2));
    }//GEN-LAST:event_mnItKurangActionPerformed

    private void mnItClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItClearActionPerformed
        txtData1.setText("");
        txtData2.setText("");
        txtHasil.setText("");
    }//GEN-LAST:event_mnItClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnBantuan;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnItBagi;
    private javax.swing.JMenuItem mnItClear;
    private javax.swing.JMenu mnItHitung;
    private javax.swing.JMenuItem mnItKali;
    private javax.swing.JMenuItem mnItKurang;
    private javax.swing.JMenuItem mnItTambah;
    private javax.swing.JMenu mnProses;
    private javax.swing.JTextField txtData1;
    private javax.swing.JTextField txtData2;
    private javax.swing.JTextField txtHasil;
    // End of variables declaration//GEN-END:variables
}
